import unittest
import json
import sys
import os
from unittest.mock import patch, MagicMock

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from fastapi.testclient import TestClient
import httpx

from backend.main import app
from backend.core.config import settings
from backend.database.database import engine, Base, SessionLocal
from backend.database.models import User, Assessment
from backend.core.security import get_password_hash
from backend.services.nvidia_ai_service import NvidiaAIService, nvidia_ai_service
from backend.services.prediction_service import prediction_service
from backend.api.dependencies import login_rate_limiter, prediction_rate_limiter

client = TestClient(app)


class TestNvidiaExplainableAI(unittest.TestCase):
    """
    Phase B — Explainable AI with NVIDIA test suite.
    Strictly isolated: 0 real network calls to external APIs.
    """

    @classmethod
    def setUpClass(cls):
        Base.metadata.create_all(bind=engine)
        login_rate_limiter.client_records.clear()
        prediction_rate_limiter.client_records.clear()

        db = SessionLocal()
        db.query(User).filter(User.email == "ai_evaluator@bank.com").delete()
        db.commit()

        test_user = User(
            email="ai_evaluator@bank.com",
            password_hash=get_password_hash("Secret123!"),
            role="CREDIT_OFFICER",
            is_active=True
        )
        db.add(test_user)
        db.commit()
        db.close()

        login_res = client.post(
            "/api/auth/login",
            json={"email": "ai_evaluator@bank.com", "password": "Secret123!"}
        )
        token = login_res.json().get("access_token")
        cls.headers = {"Authorization": f"Bearer {token}"}

        cls.sample_applicant = {
            "status_checking_account": "A14",
            "duration_in_months": 18,
            "credit_history": "A32",
            "purpose": "A40",
            "credit_amount": 3000,
            "savings_account": "A62",
            "present_employment_since": "A74",
            "installment_rate": 2,
            "personal_status_sex": "A93",
            "other_debtors_guarantors": "A101",
            "present_residence_since": 3,
            "property": "A121",
            "age_in_years": 40,
            "other_installment_plans": "A143",
            "housing": "A152",
            "existing_credits": 1,
            "job": "A173",
            "num_people_liable": 1,
            "telephone": "A192",
            "foreign_worker": "A201"
        }

        cls.sample_ml_result = {
            "default_probability": 0.125,
            "default_probability_pct": "12.50%",
            "predicted_class": 0,
            "decision_threshold": 0.35,
            "risk_category": "LOW RISK",
            "credit_decision": "APPROVED",
            "model_name": "LogisticRegression",
            "model_version": "1.0.0",
            "risk_factors": ["Moderate loan amount"],
            "protective_factors": ["No checking deficit", "Tenured employment"]
        }

    # 1. NVIDIA service success
    def test_01_nvidia_service_success(self):
        """1. Verify successful NVIDIA AI inference response parsing and metadata."""
        mock_response = {
            "explanation": "The model associated stable employment with lower predicted risk.",
            "summary": "Executive underwriting summary generated by NVIDIA AI.",
            "insights": [
                "Maintain scheduled monthly direct debit.",
                "Eligible for tier-1 renewal upon 6 months timely repayment.",
                "Debt-to-income profile is conservative."
            ],
            "provider": "NVIDIA AI",
            "model": "meta/llama-3.2-11b-vision-instruct",
            "status": "SUCCESS",
            "generated_at": "2026-09-29T12:00:00"
        }

        service = NvidiaAIService()
        with patch.object(settings, "NVIDIA_API_KEY", "nvapi-mock-valid-key"):
            with patch.object(NvidiaAIService, "_call_nvidia_api", return_value=mock_response):
                res = service.generate_explanation(self.sample_applicant, self.sample_ml_result)
                self.assertEqual(res["status"], "SUCCESS")
                self.assertEqual(res["provider"], "NVIDIA AI")
                self.assertEqual(res["summary"], "Executive underwriting summary generated by NVIDIA AI.")
                self.assertIn("lower predicted risk", res["explanation"])
                self.assertEqual(len(res["insights"]), 3)

    # 2. NVIDIA API failure
    def test_02_nvidia_api_failure(self):
        """2. Verify graceful fallback when NVIDIA API returns HTTP error (500)."""
        mock_resp = MagicMock()
        mock_resp.status_code = 500

        service = NvidiaAIService()
        with patch.object(settings, "NVIDIA_API_KEY", "nvapi-mock-key"):
            with patch.object(NvidiaAIService, "_call_nvidia_api", side_effect=httpx.HTTPStatusError("500 Internal Server Error", request=MagicMock(), response=mock_resp)):
                res = service.generate_explanation(self.sample_applicant, self.sample_ml_result)
                self.assertEqual(res["status"], "FALLBACK")
                self.assertEqual(res["provider"], "Deterministic Fallback")
                self.assertTrue(len(res["summary"]) > 0)
                self.assertTrue(len(res["explanation"]) > 0)
                self.assertIsInstance(res["insights"], list)

    # 3. Missing NVIDIA API key
    def test_03_missing_nvidia_api_key(self):
        """3. Verify deterministic fallback when NVIDIA_API_KEY is empty or placeholder."""
        service = NvidiaAIService()
        with patch.object(settings, "NVIDIA_API_KEY", ""):
            res = service.generate_explanation(self.sample_applicant, self.sample_ml_result)
            self.assertEqual(res["status"], "FALLBACK")
            self.assertEqual(res["provider"], "Deterministic Fallback")
            self.assertIn("approval", res["summary"].lower())

    # 4. NVIDIA timeout
    def test_04_nvidia_timeout(self):
        """4. Verify timeout handling triggers deterministic fallback without crashing."""
        service = NvidiaAIService()
        with patch.object(settings, "NVIDIA_API_KEY", "nvapi-mock-key"):
            with patch.object(NvidiaAIService, "_call_nvidia_api", side_effect=httpx.TimeoutException("Read timed out")):
                res = service.generate_explanation(self.sample_applicant, self.sample_ml_result)
                self.assertEqual(res["status"], "FALLBACK")
                self.assertEqual(res["provider"], "Deterministic Fallback")

    # 5. Malformed NVIDIA response
    def test_05_malformed_nvidia_response(self):
        """5. Verify malformed or incomplete JSON from NVIDIA triggers deterministic fallback."""
        service = NvidiaAIService()
        with patch.object(settings, "NVIDIA_API_KEY", "nvapi-mock-key"):
            with patch.object(NvidiaAIService, "_call_nvidia_api", side_effect=ValueError("Malformed JSON")):
                res = service.generate_explanation(self.sample_applicant, self.sample_ml_result)
                self.assertEqual(res["status"], "FALLBACK")
                self.assertEqual(res["provider"], "Deterministic Fallback")
                self.assertIsInstance(res["insights"], list)

    # 6. Deterministic fallback
    def test_06_deterministic_fallback(self):
        """6. Verify deterministic fallback produces correct structure and AI source."""
        service = NvidiaAIService()
        for decision in ["APPROVED", "REJECTED", "REVIEW"]:
            ml_case = dict(self.sample_ml_result)
            ml_case["credit_decision"] = decision
            res = service._generate_fallback(self.sample_applicant, ml_case)
            self.assertEqual(res["provider"], "Deterministic Fallback")
            self.assertEqual(res["status"], "FALLBACK")
            self.assertIsInstance(res["insights"], list)
            self.assertGreaterEqual(len(res["insights"]), 1)

    # 7. ML prediction without NVIDIA
    def test_07_ml_prediction_without_nvidia(self):
        """7. Verify ML scoring engine runs 100% autonomously without external AI."""
        ml_output = prediction_service.predict(self.sample_applicant)
        self.assertIn("default_probability", ml_output)
        self.assertIn("predicted_class", ml_output)
        self.assertIn("risk_category", ml_output)
        self.assertEqual(ml_output["decision_threshold"], 0.35)
        self.assertIsInstance(ml_output["default_probability"], float)

    # 8. NVIDIA cannot change probability
    def test_08_nvidia_cannot_change_probability(self):
        """8. CRITICAL: NVIDIA layer must never alter or mutate default_probability."""
        original_prob = self.sample_ml_result["default_probability"]
        service = NvidiaAIService()
        service.generate_explanation(self.sample_applicant, self.sample_ml_result)
        self.assertEqual(self.sample_ml_result["default_probability"], original_prob)

    # 9. NVIDIA cannot change threshold
    def test_09_nvidia_cannot_change_threshold(self):
        """9. CRITICAL: NVIDIA layer must never alter decision threshold (0.35)."""
        service = NvidiaAIService()
        service.generate_explanation(self.sample_applicant, self.sample_ml_result)
        self.assertEqual(self.sample_ml_result["decision_threshold"], 0.35)

    # 10. NVIDIA cannot change risk category
    def test_10_nvidia_cannot_change_risk_category(self):
        """10. CRITICAL: NVIDIA layer must never alter calculated risk category."""
        original_cat = self.sample_ml_result["risk_category"]
        service = NvidiaAIService()
        service.generate_explanation(self.sample_applicant, self.sample_ml_result)
        self.assertEqual(self.sample_ml_result["risk_category"], original_cat)

    # 11. API key is never returned
    def test_11_api_key_is_never_returned(self):
        """11. SECURITY: NVIDIA_API_KEY must NEVER be leaked in API responses."""
        secret_test_key = "nvapi-SECRET-NEVER-LEAK-THIS-KEY-12345"
        mock_response = {
            "explanation": "Test explanation.",
            "summary": "Test summary.",
            "insights": ["Insight 1"],
            "provider": "NVIDIA AI",
            "model": "meta/llama-3.2-11b-vision-instruct",
            "status": "SUCCESS",
            "generated_at": "2026-09-29T12:00:00"
        }

        with patch.object(settings, "NVIDIA_API_KEY", secret_test_key):
            with patch.object(NvidiaAIService, "_call_nvidia_api", return_value=mock_response):
                create_res = client.post(
                    "/api/predictions",
                    headers=self.headers,
                    json={"applicant": self.sample_applicant}
                )
                self.assertEqual(create_res.status_code, 201)
                self.assertNotIn(secret_test_key, create_res.text)

                pred_id = create_res.json()["prediction_id"]
                detail_res = client.get(f"/api/predictions/{pred_id}", headers=self.headers)
                self.assertEqual(detail_res.status_code, 200)
                self.assertNotIn(secret_test_key, detail_res.text)

                list_res = client.get("/api/predictions", headers=self.headers)
                self.assertEqual(list_res.status_code, 200)
                self.assertNotIn(secret_test_key, list_res.text)

    # 12. AI fields appear in prediction response
    def test_12_ai_fields_appear_in_prediction_response(self):
        """12. Verify ai_explanation, ai_summary, ai_insights, ai_provider appear in API & DB."""
        mock_response = {
            "explanation": "Comprehensive model decision rationale.",
            "summary": "Executive underwriting brief.",
            "insights": ["Mitigate via collateral", "Monitor cash flow"],
            "provider": "NVIDIA AI",
            "model": "meta/llama-3.2-11b-vision-instruct",
            "status": "SUCCESS",
            "generated_at": "2026-09-29T12:00:00"
        }

        with patch.object(NvidiaAIService, "_call_nvidia_api", return_value=mock_response):
            response = client.post(
                "/api/predictions",
                headers=self.headers,
                json={"applicant": self.sample_applicant}
            )

        self.assertEqual(response.status_code, 201)
        data = response.json()
        self.assertEqual(data["ai_explanation"], "Comprehensive model decision rationale.")
        self.assertEqual(data["ai_summary"], "Executive underwriting brief.")
        self.assertEqual(data["ai_insights"], ["Mitigate via collateral", "Monitor cash flow"])
        self.assertEqual(data["ai_provider"], "NVIDIA AI")

        # Verify DB persistence
        db = SessionLocal()
        record = db.query(Assessment).filter(Assessment.id == data["prediction_id"]).first()
        self.assertIsNotNone(record)
        self.assertEqual(record.ai_explanation, "Comprehensive model decision rationale.")
        self.assertEqual(record.ai_summary, "Executive underwriting brief.")
        self.assertEqual(record.ai_provider, "NVIDIA AI")
        self.assertIsNotNone(record.ai_insights)
        db.close()


if __name__ == "__main__":
    unittest.main()
